import { Router } from "express";
import { staffApprovalRouter } from "./staff-approval.routes.js";
import { staffAttendanceRouter } from "./staff-attendance.routes.js";
import { staffAuditRouter } from "./staff-audit.routes.js";
import { staffBiometricRouter } from "./staff-biometric.routes.js";
import { staffCommissionRouter } from "./staff-commission.routes.js";
import { staffIntelligenceRouter } from "./staff-intelligence.routes.js";
import { staffLeaveRouter } from "./staff-leave.routes.js";
import { staffManpowerForecastRouter } from "./staff-manpower-forecast.routes.js";
import { staffMasterRouter } from "./staff-master.routes.js";
import { staffMobileRouter } from "./staff-mobile.routes.js";
import { staffMobileSyncRouter } from "./staff-mobile-sync.routes.js";
import { staffPayrollRouter } from "./staff-payroll.routes.js";
import { staffPayrollComplianceRouter } from "./staff-payroll-compliance.routes.js";
import { staffPerformanceRouter } from "./staff-performance.routes.js";
import { staffReplacementEngineRouter } from "./staff-replacement-engine.routes.js";
import { staffReportsRouter } from "./staff-reports.routes.js";
import { staffRosterOptimizerRouter } from "./staff-roster-optimizer.routes.js";
import { staffScheduleRouter } from "./staff-schedule.routes.js";
import { staffTaskRouter } from "./staff-task.routes.js";
import { staffTipsRouter } from "./staff-tips.routes.js";
import { staffWhatsappNotificationRouter } from "./staff-whatsapp-notification.routes.js";
import { staffOsCapabilityRouter } from "./staff-os-route-utils.js";

export const staffOsRouter = Router();

staffOsRouter.use(staffOsCapabilityRouter("staff-app-master", /^\/staff-os\/(?:(?:staff-categories|attendance-masters|leave-masters|shift-masters|attendance-categories|target-incentives|service-assignments|fine-penalties|allowance-deductions|payroll-structures|bulk-employee-update)(?:\/|$)|staff(?:$|\/(?:media|[^/]+(?:$|\/(?:status|login|documents|skills)(?:\/|$)))))/, staffMasterRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-schedules", /^\/staff-os\/(?:schedules|shift-swaps|branch-transfer)(?:\/|$)/, staffScheduleRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-attendance", /^\/staff-os\/attendance(?:$|\/(?:clock-in|clock-out|break-start|break-end|overtime-summary|correction)$)/, staffAttendanceRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-leave", /^\/staff-os\/(?:leaves|leave-calendar|leave-balances)(?:\/|$)/, staffLeaveRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-payroll", /^\/staff-os\/payroll(?:\/|$)/, staffPayrollRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-commissions", /^\/staff-os\/commissions(?:\/|$)/, staffCommissionRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-tips", /^\/staff-os\/tips(?:\/|$)/, staffTipsRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-performance", /^\/staff-os\/(?:performance|leaderboard)(?:\/|$)/, staffPerformanceRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-intelligence", /^\/staff-os\/intelligence(?:\/|$)/, staffIntelligenceRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-mobile", /^\/staff-os\/mobile\/(?:dashboard|today|payroll|targets|request-leave)(?:\/|$)/, staffMobileRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-tasks", /^\/staff-os\/tasks(?:\/|$)/, staffTaskRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-audit", /^\/staff-os\/audit(?:\/|$)/, staffAuditRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-reports", /^\/staff-os\/staff-sales(?:\/|$)/, staffReportsRouter));
staffOsRouter.use((req, res, next) => /^\/staff-os\/reports(?:\/|$)/.test(req.path) ? staffReportsRouter(req, res, next) : next());
staffOsRouter.use(staffOsCapabilityRouter("staff-app-biometric", /^\/staff-os\/(?:biometric(?:\/|$)|attendance\/(?:biometric-center|camera-punch|risks|fraud-scan|payroll-preview)(?:\/|$)|owner-alerts(?:\/|$))/, staffBiometricRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-notifications", /^\/staff-os\/notifications(?:\/|$)/, staffWhatsappNotificationRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-payroll-compliance", /^\/staff-os\/(?:payroll-compliance|salary-revisions|staff\/[^/]+\/salary-(?:history|revision|revisions))(?:\/|$)/, staffPayrollComplianceRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-replacement", /^\/staff-os\/replacement(?:\/|$)/, staffReplacementEngineRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-sync", /^\/staff-os\/mobile\/(?:devices|snapshot|sync|conflicts)(?:\/|$)/, staffMobileSyncRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-approvals", /^\/staff-os\/approvals(?:\/|$)/, staffApprovalRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-roster", /^\/staff-os\/roster(?:\/|$)/, staffRosterOptimizerRouter));
staffOsRouter.use(staffOsCapabilityRouter("staff-app-forecasting", /^\/staff-os\/manpower(?:\/|$)/, staffManpowerForecastRouter));
