import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const routes = readFileSync('src/app/app.routes.ts', 'utf8');
const sidebar = readFileSync('src/app/layout/app-sidebar.component.ts', 'utf8');
const page = readFileSync('src/app/pages/pos/happy-hours/happy-hours-page.component.ts', 'utf8');
const template = readFileSync('src/app/pages/pos/happy-hours/happy-hours-page.component.html', 'utf8');
const backend = readFileSync('../backend-rust/src/routes/pos.rs', 'utf8');
const intelligence = readFileSync('../backend-rust/src/services/happy_hours_service.rs', 'utf8');
const campaignMigration = readFileSync('../backend-rust/migrations/0127_happy_hours_campaign_audiences.sql', 'utf8');
const marketMigration = readFileSync('../backend-rust/migrations/0128_happy_hours_market_aware.sql', 'utf8');
const contextMigration = readFileSync('../backend-rust/migrations/0131_happy_hours_context_aware.sql', 'utf8');
const autoSunsetMigration = readFileSync('../backend-rust/migrations/0134_happy_hours_auto_sunset.sql', 'utf8');
const governanceMigration = readFileSync('../backend-rust/migrations/0139_happy_hours_governance.sql', 'utf8');
const couponApprovalMigration = readFileSync('../backend-rust/migrations/0140_happy_hours_coupon_abuse_approval.sql', 'utf8');
const advancedCouponFraudMigration = readFileSync('../backend-rust/migrations/0182_happy_hours_advanced_coupon_fraud.sql', 'utf8');
const backendMain = readFileSync('../backend-rust/src/main.rs', 'utf8');
const tenantMiddleware = readFileSync('../backend-rust/src/middleware/tenant.rs', 'utf8');

test('Happy Hours management is wired to the existing POS rule engine', () => {
  assert.match(routes, /path: 'pos\/happy-hours'/);
  assert.match(sidebar, /route: '\/pos\/happy-hours'/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/rules/);
  assert.match(backend, /"\/pos\/happy-hours\/rules\/:id"/);
  assert.match(backend, /update_happy_hour_rule/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/control-tower/);
  assert.match(backend, /get_happy_hours_control_tower/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/intelligence/);
  assert.match(backend, /get_happy_hours_intelligence/);
  assert.match(intelligence, /repeated_coupon_usage/);
  assert.match(intelligence, /no_show_risks/);
  assert.match(intelligence, /inventory_offer_signals/);
  assert.match(intelligence, /staff_offer_signals/);
  assert.match(page, /\/api\/v1\/pos\/coupons/);
  assert.match(template, /Promotion calendar/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/audiences/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/campaign-links/);
  assert.match(backend, /save_happy_hour_audience/);
  assert.match(backend, /save_happy_hour_campaign_link/);
  assert.match(campaignMigration, /pos_happy_hour_audiences/);
  assert.match(campaignMigration, /pos_happy_hour_campaign_links/);
  assert.match(template, /Campaign audiences/);
  assert.match(template, /Campaign links/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/market-aware\/observations/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/market-aware\/evaluate/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/market-aware\/suggestions/);
  assert.match(backend, /evaluate_happy_hour_market_offer/);
  assert.match(backend, /save_happy_hour_market_suggestion/);
  assert.match(marketMigration, /pos_market_price_observations/);
  assert.match(marketMigration, /pos_happy_hour_market_suggestions/);
  assert.match(template, /Market-aware offers/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/context-aware\/evaluate/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/context-aware\/suggestions/);
  assert.match(backend, /evaluate_happy_hour_context_offer/);
  assert.match(backend, /save_happy_hour_context_suggestion/);
  assert.match(contextMigration, /pos_happy_hour_context_suggestions/);
  assert.match(contextMigration, /'bundle','channel','lead_time','weather_event','member_wallet'/);
  assert.match(template, /Member \/ wallet/);
  assert.match(intelligence, /redeem_membership_credit/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/auto-sunset\/scan/);
  assert.match(backend, /scan_happy_hour_auto_sunset/);
  assert.match(autoSunsetMigration, /pos_happy_hour_auto_sunset_decisions/);
  assert.match(backendMain, /run_auto_sunset_worker/);
  assert.match(template, /Auto-sunset/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/branch-leaderboard/);
  assert.match(backend, /get_happy_hour_branch_leaderboard/);
  assert.match(intelligence, /branch_leaderboard_score/);
  assert.match(template, /Branch leaderboard/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/client-returns/);
  assert.match(backend, /get_happy_hour_client_returns/);
  assert.match(intelligence, /client_return_tracker/);
  assert.match(template, /Client Return Tracker/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/elasticity-pricing/);
  assert.match(backend, /get_happy_hour_elasticity_pricing/);
  assert.match(intelligence, /elasticity_pricing/);
  assert.match(template, /Elasticity \+ Profit Pricing/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/rule-conflicts/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/simulate/);
  assert.match(backend, /get_happy_hour_rule_conflicts/);
  assert.match(backend, /simulate_happy_hour_rule/);
  assert.match(intelligence, /build_rule_conflicts/);
  assert.match(template, /Simulation sandbox/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/approvals/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/anomalies/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/budget/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/audit/);
  assert.match(page, /\/api\/v1\/settings\/integrations\/webhooks/);
  assert.match(backend, /request_happy_hour_approval/);
  assert.match(backend, /scan_happy_hour_anomalies/);
  assert.match(governanceMigration, /pos_happy_hour_approval_requests/);
  assert.match(governanceMigration, /pos_happy_hour_anomalies/);
  assert.match(governanceMigration, /pos_happy_hour_budgets/);
  assert.match(governanceMigration, /integration_webhook_deliveries/);
  assert.match(template, /Discount approvals/);
  assert.match(template, /Anomaly inbox/);
  assert.match(template, /Webhook deliveries/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/discount-approvals/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/coupon-abuse\/alerts/);
  assert.match(backend, /request_discount_approval/);
  assert.match(backend, /scan_coupon_abuse/);
  assert.match(intelligence, /ensure_discount_approval_for_finalize/);
  assert.match(intelligence, /scan_coupon_abuse_for_sale/);
  assert.match(couponApprovalMigration, /pos_discount_approval_requests/);
  assert.match(couponApprovalMigration, /pos_coupon_abuse_alerts/);
  assert.match(couponApprovalMigration, /INTERVAL '15 minutes'/);
  assert.match(template, /Invoice discount approvals/);
  assert.match(template, /Coupon abuse alerts/);
  assert.match(page, /\/api\/v1\/pos\/coupons\/analytics/);
  assert.match(page, /\/api\/v1\/pos\/happy-hours\/fraud-guard\/cases/);
  assert.match(backend, /rule_approval_assessment/);
  assert.match(backend, /coupon per-client usage limit is reached/);
  assert.match(intelligence, /role_discount_limit_bps/);
  assert.match(intelligence, /statistical_discount_anomaly/);
  assert.match(intelligence, /scan_fraud_cases/);
  assert.match(advancedCouponFraudMigration, /per_client_limit/);
  assert.match(advancedCouponFraudMigration, /target_client_segments/);
  assert.match(advancedCouponFraudMigration, /rule_snapshot_json/);
  assert.match(advancedCouponFraudMigration, /pos_happy_hour_fraud_cases/);
  assert.match(advancedCouponFraudMigration, /Regional Head/);
  assert.match(tenantMiddleware, /regional_head/);
  assert.match(template, /Risk-scored fraud guard/);
  assert.match(template, /Coupon return on discount/);
  assert.match(page, /\/api\/v1\/inventory\?pageSize=200/);
  assert.doesNotMatch(page, /'\/api\/v1\/products/);
  assert.match(page, /catalogFailures\.add\(label\)/);
  assert.match(page, /Unable to load \$\{\[\.\.\.this\.catalogFailures\]\.join\(', '\)\}/);
  assert.match(template, /\{\{ catalogError\(\) \}\}/);
});
