import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const root = new URL('../src/app/pages/marketing/', import.meta.url);
const ts = readFileSync(new URL('marketing-leads-page.component.ts', root), 'utf8');
const html = readFileSync(new URL('marketing-leads-page.component.html', root), 'utf8');
const booking = readFileSync(new URL('../booking/public-booking-page.component.ts', root), 'utf8');
const governanceMigration = readFileSync(new URL('../../../../../backend-rust/migrations/0221_marketing_governance.sql', root), 'utf8');
const deliveryRepository = readFileSync(new URL('../../../../../backend-rust/src/repositories/benefit_notification_repository.rs', root), 'utf8');

test('marketing win-back workspace uses real API data and consent-gated campaigns', () => {
  assert.match(ts, /\/marketing\/win-back\?inactiveDays=/);
  assert.match(ts, /\/marketing\/win-back\/results/);
  assert.match(ts, /\/marketing\/client-intelligence/);
  assert.match(html, /Actionable clients/);
  assert.match(ts, /segmentKeys/);
  assert.match(html, /Smart Segments/);
  assert.match(ts, /\/marketing\/advisor\/recommend/);
  assert.match(ts, /\/marketing\/advisor\/review/);
  assert.match(ts, /\/marketing\/offers/);
  assert.match(ts, /\/marketing\/offers\/\$\{offer\.id\}\/approve/);
  assert.match(html, /Create controlled offer/);
  assert.match(html, /Allow membership stacking/);
  assert.match(html, /Allow package stacking/);
  assert.match(ts, /\/notifications\/marketing-coverage/);
  assert.match(ts, /\/notifications\/marketing-test/);
  assert.match(ts, /campaign-approval/);
  assert.match(html, /Campaign builder/);
  assert.match(html, /WhatsApp failure → SMS fallback/);
  assert.match(html, /Submit for approval/);
  assert.match(ts, /\/marketing\/automations/);
  assert.match(html, /Automation rules/);
  assert.match(html, /Frequency cap/);
  assert.match(html, /Pause/);
  assert.match(ts, /\/message-templates/);
  assert.match(html, /Template library/);
  assert.match(html, /Generate with AI/);
  assert.match(ts, /\/marketing\/attribution/);
  assert.match(html, /Booking &amp; Revenue Attribution/);
  assert.match(html, /Net revenue/);
  assert.match(html, /reactivation.*ROI/);
  assert.match(booking, /marketing_campaign:/);
  assert.match(html, /client_name/);
  assert.match(html, /Supporting CRM evidence/);
  assert.match(html, /AI Offer Advisor/);
  assert.match(html, /activeSection === 'leads'/);
  assert.match(html, /Add lead/);
  assert.match(ts, /\/marketing\/leads\/advice/);
  assert.match(html, /AI Priority/);
  assert.match(html, /Suggested message/);
  assert.match(html, /convertedAppointmentId/);
  assert.match(ts, /\/marketing\/governance/);
  assert.match(ts, /campaign-send/);
  assert.match(html, /Permissions, Consent &amp; Governance/);
  assert.match(governanceMigration, /marketing_sensitive_excluded/);
  assert.match(deliveryRepository, /frequency_cap_days/);
  assert.match(deliveryRepository, /quiet_start/);
  assert.match(html, /activeSection = 'campaigns'/);
  assert.match(html, /leadSection = 'followups'/);
  for (const tab of ['Overview', 'AI Opportunities', 'Segments', 'Campaigns', 'Automations', 'Offers', 'Templates', 'Outbox', 'Leads', 'Analytics']) assert.match(html, new RegExp(`>${tab}<`));
  assert.match(html, /\(click\)="reviewAdvisor\('accepted'\)"/);
  assert.doesNotMatch(html, /advisor.*Create campaign/i);
  assert.doesNotMatch(ts, /fake|dummy|sample client/i);
});
