pub mod accounting_service;
pub mod ai_action_service;
pub mod ai_briefing_service;
pub mod ai_channel_service;
pub mod ai_concierge_service;
pub mod ai_copilot_governance;
pub mod ai_copilot_tools;
pub mod ai_cross_module_tools;
#[cfg(test)]
mod ai_evaluation_tests;
pub mod ai_prediction_service;
pub mod ai_scope_service;
pub mod ai_scoped_copilot_tools;
pub mod ai_tool_dispatcher;
pub mod ai_what_if_service;
pub mod ai_workforce_service;
pub mod analytics_service;
pub mod appointment_reporting_service;
pub mod auth_service;
pub mod balance_sheet_service;
pub mod benefit_notification_service;
pub mod birthday_anniversary_service;
pub mod booking_intelligence_service;
pub mod booking_service;
pub mod branch_service;
pub mod cash_drawer_service;
pub mod client_export_governance_service;
pub mod client_service;
pub mod compliance_provider_service;
pub mod customer_portal_service;
pub mod entitlement_service;
pub mod fitness_service;
pub mod growth_intelligence_service;
pub mod happy_hours_service;
pub mod integration_service;
pub mod inventory_adjustment_service;
pub mod inventory_controls_service;
pub mod inventory_governance_service;
pub mod inventory_transfer_service;
pub mod invoice_delivery;
pub mod invoice_numbering_service;
pub mod invoice_pdf;
pub mod kiosk_service;
pub mod language_settings_service;
pub mod laundry_service;
pub mod live_consultation_service;
pub mod marketing_advisor_service;
pub mod marketing_lead_scoring_service;
pub mod membership_auto_renew_service;
pub mod membership_service;
pub mod migration_adapter_service;
pub mod migration_file_service;
pub mod migration_large_import_service;
pub mod migration_proof_service;
pub mod migration_provider_service;
pub mod migration_service;
pub mod operations_service;
pub mod organization_service;
pub mod outgoing_funds_service;
pub mod package_service;
pub mod payment_dispute_service;
pub mod payment_gateway_service;
pub mod payment_platform_service;
pub mod pos_enterprise_service;
pub mod profit_governance_service;
pub mod purchase_bill_drafts_service;
pub mod purchase_service;
pub mod razorpay_payment_service;
pub mod retention_service;
pub mod saas_service;
pub mod security_service;
pub mod service_pricing_service;
pub mod service_settings_service;
pub mod sms_center_service;
pub mod sso_service;
pub mod staff_advance_service;
pub mod staff_advanced_service;
pub mod staff_ai_scribe_service;
pub mod staff_ai_service;
pub mod staff_app_service;
pub mod staff_attendance_service;
pub mod staff_enterprise_service;
pub mod staff_hrms_service;
pub mod staff_leave_service;
pub mod staff_notification_service;
pub mod staff_operations_service;
pub mod staff_payroll_service;
pub mod staff_schedule_service;
pub mod staff_service;
pub mod stock_audit_service;
pub mod team_chat_service;
pub mod wallet_service;
pub mod webauthn_service;

#[cfg(test)]
mod staff_lifecycle_chain_tests;

#[cfg(test)]
mod staff_payroll_regeneration_tests;

pub mod inventory_reorder_forecast_service;

pub mod report_export_service;
